[package]
name = "mud-blog-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
mud-blog = { path = ".." }

[[bin]]
name = "parse_markdown_post"
path = "fuzz_targets/parse_markdown_post.rs"
test = false
doc = false
bench = false
